name: "C-Project Workflow"
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: "GCC VERSION"
        run: gcc --version
      - name: "Check out repository"
        uses: actions/checkout@v3
      - name: "Path"
        run: pwd
      - name: "All files"
        run: ls -aR
      - name: "Compile Project"
        run: make --file=Makefile all
      - name: "Test"
        run: ./program test
